const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const SHOW_ALL = 'SHOW_ALL';
const SHOW_COMPLETED = 'SHOW_COMPLETED';
const SHOW_ACTIVE = 'SHOW_ACTIVE';
const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export {
	ADD_TODO,
	TOGGLE_TODO,
	REMOVE_TODO,
	SHOW_ALL,
	SHOW_COMPLETED,
	SHOW_ACTIVE,
	SET_VISIBILITY_FILTER
};